name: rrule
description: 'ðŸ” Recurrence rule parsing & calculation as defined in the iCalendar RFC'
version: 0.2.0
homepage: https://github.com/JonasWanke/rrule

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  intl: ^0.17.0
  meta: ^1.3.0
  supercharged_dart: ^2.0.0

dev_dependencies:
  extra_pedantic: ^1.3.0
  test: ^1.16.8
  # test_coverage: ^0.5.0
